OnlineElection/Controllers/Admin/MessegingController.cs
using OnlineElection.BLL.Repository;
using OnlineElection.Domain.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineElection.Controllers.Admin
{
    public class MessegingController : Controller
    {

        BatchRepository _batchRepository = new BatchRepository();
        MessegeRepository _messageRepository = new MessegeRepository();

        // GET: Messeging
        public ActionResult Index()
        {

            ViewBag.FOCbatchDetails = _batchRepository.GetFOCBatchDetails();
            
            ViewBag.FOBbatchDetails = _batchRepository.GetFOBBatchDetails();

            ViewBag.FOEbatchDetails = _batchRepository.GetFOEBatchDetails();

            //get the user ID
            string user = "21781DD9-4A1C-4DFB-933F-21633B94B61B";
            ViewBag.unreadCount = _messageRepository.unreadCount(user);
            return View("~/ViewsAdmin/Messeging/Index.cshtml");
        }

        public ActionResult Messeges(string id)
        {
            ViewBag.MessegeID = id;


            //get the user ID
            string user = "21781DD9-4A1C-4DFB-933F-21633B94B61B";
            ViewBag.unreadCount = _messageRepository.unreadCount(user);
            return View("~/ViewsAdmin/Messeging/Messeges.cshtml");
        }

        // POST: Messeging/SendMessege
        [HttpPost]
        public ActionResult SendMessege(FormCollection collection)
        {
            try
            {
                List<BatchDetailsViewModel> batchFOC = new List<BatchDetailsViewModel>();
                List<BatchDetailsViewModel> batchFOB = new List<BatchDetailsViewModel>();
                List<BatchDetailsViewModel> batchFOE = new List<BatchDetailsViewModel>();

                List<string> trueVal = new List<string>();

                string foc = collection["foc"];

                string fob = collection["fob"];

                string foe = collection["foe"];

                batchFOC = _batchRepository.GetFOCBatchDetails().ToList();
                batchFOB = _batchRepository.GetFOBBatchDetails().ToList();
                batchFOE = _batchRepository.GetFOEBatchDetails().ToList();

                if (foc != "on")
                {
                    foreach (var item in batchFOC)
                    {
                        string valB = collection[item.batch_ID];
                        if (valB == "on")
                        {
                            trueVal.Add(item.batch_ID);
                        }
                    }
                }
                else
                {
                    trueVal.Add("foc");
                }

                if (fob != "on")
                {
                    foreach (var item in batchFOB)
                    {
                        string valB = collection[item.batch_ID];
                        if (valB == "on")
                        {
                            trueVal.Add(item.batch_ID);
                        }
                    }
                }
                else
                {
                    trueVal.Add("fob");
                }


                if (foe != "on")
                {
                    foreach (var item in batchFOE)
                    {
                        string valB = collection[item.batch_ID];
                        if (valB == "on")
                        {
                            trueVal.Add(item.batch_ID);
                        }
                    }
                }
                else
                {
                    trueVal.Add("foe");
                }



                string subject = collection["txtSubject"];
                string body = collection["TextAreaInput"];
               
               bool answer = _batchRepository.sendMessege(trueVal,subject,body);



                //These are for the Index Needed
                    ViewBag.FOCbatchDetails = _batchRepository.GetFOCBatchDetails();

                    ViewBag.FOBbatchDetails = _batchRepository.GetFOBBatchDetails();

                    ViewBag.FOEbatchDetails = _batchRepository.GetFOEBatchDetails();

                return View("~/ViewsAdmin/Messeging/Index.cshtml");
            }
            catch(Exception e)
            {
                return View("~/ViewsAdmin/Messeging/Index.cshtml");
            }
        }


        public ActionResult GetMessView()
        {
            string user = "21781DD9-4A1C-4DFB-933F-21633B94B61B";
            return PartialView("~/ViewsAdmin/Shared/_MessgingInterfaceMessegeList.cshtml", _messageRepository.GetAllMessages(user));
        }


        public ActionResult GetMessConvView(int id)
        {
            //int id = 4;
            return PartialView("~/ViewsAdmin/Shared/_MessagesConversations.cshtml", _messageRepository.GetConversation(id));
        }

    }
}

OnlineElection/Controllers/VoteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineElection.BLL.Repository;

namespace OnlineElection.Controllers
{

    public class VoteController : Controller
    {
        CandidateRepository _candidateRepository = new CandidateRepository();

        // GET: Vote
        public ActionResult Index()
        {


            //ViewBag.candidateList = _candidateRepository.GetAllCandidates();

            return View();
        }

        //Sasindu 
        // GET: Vote

        //please get vote id as a parameter
        //public ActionResult VotingPage(string poll_id)
        public ActionResult VotingPage()
        {
            ViewData["Message"] = "Vote Name";
            ViewData["Description"] = "Vote Description";
            string poll_id = "d9e2a9c5-e2ca-41b9-a811-adab5647a76f";

            Session["pollID"] = poll_id;

            ViewBag.candidateList = _candidateRepository.GetPollSpecificCandidates(poll_id);

            return View();
        }


        //Sasindu
        // POST: Vote/VoteSubmit
        [HttpPost]
        public ActionResult VoteSubmit()
        {
            try
            {
                //get the person ID of logged in student
                string loggedid = "D358BC1A-F92E-4C5B-8F16-EE0C15086BE0";

                //get the poll iD
                //string PollID = "d9e2a9c5-e2ca-41b9-a811-adab5647a76f";
                string PollID = (string)Session["pollID"];
                //get the candidate ID
                string candidateId = Request.Form["selctedCandidate"];
                bool result = _candidateRepository.VoteStubmit(loggedid, PollID, candidateId);



                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }



        // GET: Vote/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Vote/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Vote/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Vote/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Vote/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
                // var query=from m in d
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Vote/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Vote/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


        //public ActionResult ViewPolls()
        //{
        //    PollRepository poll = new PollRepository();
        //    ViewBag.poll1 = poll.ViewPolls();

        //    return View("ViewPolls");
        //}

        //[HttpGet]

        //public bool CheckPoll(string userID)
        //{
        //    Guid id = new Guid(userID);
        //    PollRepository poll = new PollRepository();
        //    bool status = true;
        //    var check = poll.CheckPoll(id);

        //    if (check != null)
        //    {
        //        status = false;
        //    }
        //    else
        //    {
        //        status = true;
        //    }
        //    return status;
        //}



    }
}

OnlineElection/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <title>@ViewBag.Title</title>

        <link rel="stylesheet" href="~/Content/materialize.css">
        <link href="~/Content/icons/material-icons.css" rel="stylesheet">
        <link href="~/Content/morris.css" rel="stylesheet">  

        @*<style>
            label {
                width: 100%;
            }

                label:after {
                    -moz-transition-property: all !important;
                    -o-transition-property: all !important;
                    -webkit-transition-property: all !important;
                    transition-property: all !important;
                    font-size: 0.8rem;
                    -moz-transform: none;
                    -ms-transform: none;
                    -o-transform: none;
                    -webkit-transform: none;
                    transform: none;
                }

                label:not(.active):after {
                    -moz-transform: translateY(-140%);
                    -ms-transform: translateY(-140%);
                    -o-transform: translateY(-140%);
                    -webkit-transform: translateY(-140%);
                    transform: translateY(-140%);
                }
        </style>*@

        @RenderSection("Styles", false)

    </head>
<body style="background-image:url('../content/images/bg.jpg')">

    <nav style="background-color:transparent">
        <div class="nav-wrapper" >
            <ul class="left hide-on-med-and-down">
                <li><a>Online Election</a></li>
                
            </ul>
            <ul id="nav-mobile" class="right hide-on-med-and-down">

                <li><a href=""> @Session["SID"]</a></li>
                <li><a href="Account/LogOut">Log Out</a></li>
                <li><a href=""></a></li>
            </ul>
        </div>
    </nav>


    <div class="row">
        <div class="col m10 offset-m1">
            @RenderBody()
        </div>
    </div>

    <script src="~/Content/vendors/jquery/dist/jquery.min.js"></script>
    <script src="~/Scripts/materialize.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>

    @RenderSection("Scripts", false/*required*/)

</body>
</html>

OnlineElection/Views/Shared/_Layout1.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @*Sasindu*@
        @*Vote Design Css*@
        <link rel="stylesheet" href="~/Content/voteDesign.css" />
        @*Navigation Css*@
        <link rel="stylesheet" href="~/Content/NewNavigation.css" />



    @*Used In votes View*@
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <link href="~/Content/icons/material-icons.css" rel="stylesheet" />
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">

</head>
<body style="background-color:#2e80ab">

    @*Side Navigation*@
    <nav class="navbar navbar-fixed-left navbar-minimal animate" role="navigation">
        <div class="navbar-toggler animate">
            <span class="menu-icon"></span>
        </div>
        <ul class="navbar-menu animate">
            <li>
                <a href="@Url.Action("Index", "Home")">             @*<a href="@Url.Action(   Action Name        ,    Controller Name)">*@ 
                    <span class="desc animate"> Home</span>
                    <span class="glyphicon glyphicon-user"></span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("About", "Home")">
                    <span class="desc animate"> About Us </span>
                    <span class="glyphicon glyphicon-info-sign"></span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("Contact", "Home")">
                    <span class="desc animate"> Contact </span>
                    <span class="glyphicon glyphicon-comment"></span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("Index", "Vote")">
                    <span class="desc animate"> Vote</span>
                    <span class="glyphicon glyphicon-comment"></span>
                </a>
            </li>

        </ul>
    </nav>
    @*End Navigation Bar*@


    <div class="container body-content" style="width:100% !important">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year -Online Election</p>
        </footer>
    </div>



    @*Script For Navigation Click*@
    <script>
        $(function () {
            $('.navbar-toggler').on('click', function(event) {
            event.preventDefault();
            $(this).closest('.navbar-minimal').toggleClass('open');
            })
        });
    </script>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

OnlineElection/Views/Shared/_LayoutAccount.cshtml
<!DOCTYPE html>
<html>
    <head>
        <title>@ViewBag.Title</title>

        <link rel="stylesheet" href="~/Content/materialize.css">
        <link href="~/Content/icons/material-icons.css" rel="stylesheet">


        

        <style>
            label {
                width: 100%;
            }

                label:after {
                    -moz-transition-property: all !important;
                    -o-transition-property: all !important;
                    -webkit-transition-property: all !important;
                    transition-property: all !important;
                    font-size: 0.8rem;
                    -moz-transform: none;
                    -ms-transform: none;
                    -o-transform: none;
                    -webkit-transform: none;
                    transform: none;
                }

                label:not(.active):after {
                    -moz-transform: translateY(-140%);
                    -ms-transform: translateY(-140%);
                    -o-transform: translateY(-140%);
                    -webkit-transform: translateY(-140%);
                    transform: translateY(-140%);
                }
        </style>

    </head>
<body style="background-image:url('../content/images/bg.jpg')">

    <div class="row">
        <div class="col m10 offset-m1">
            @RenderBody()
        </div>
    </div>

    <script src="~/Content/vendors/jquery/dist/jquery.min.js"></script>
    <script src="~/Scripts/materialize.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    @RenderSection("Scripts", false/*required*/)

</body>
</html>

OnlineElection/Views/Shared/_MessagesList.cshtml
@model IEnumerable<OnlineElection.Domain.ViewModels.MessegeViewModel>



@foreach (var item in Model)
{
    <div style="float:left;border-style:groove;width:100%" class="row">
        <img src="~/Content/Images/user.png" class="img-circle img-responsive" style="height:50px;width:50px;float:left">
        <p style="float:left">
            Name:@item.UserName
        <br />
             @item.body    
        </p>
    </div>

}

OnlineElection/Views/Shared/_MessagesListNotifications.cshtml
@model IEnumerable<OnlineElection.Domain.ViewModels.MessegeViewModel>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/lobibox.min.js"></script>
<link rel="stylesheet" href="~/Content/lobibox.min.css" />

@foreach (var item in Model)
{
    <a href="@Url.Action("getMessegeViewByClick", "Messeging" , new { id = item.MessageID })">
    <script type="text/javascript">
    var IMG_PREFIX = 'Content/Images/';
            Lobibox.notify('success', {
                position: 'bottom right',
                img: IMG_PREFIX + '~/Content/Images/@item.UserImage',
                title: '@item.UserName',
                size: 'mini',
                msg: '@item.body'
            });
    </script>
    </a>
}

OnlineElection/Views/Shared/_PollNotifications.cshtml
@model IEnumerable<OnlineElection.Domain.ViewModels.NotificationsViewModel>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/lobibox.min.js"></script>
<link rel="stylesheet" href="~/Content/lobibox.min.css" />

@foreach (var item in Model)
{
    string status = "";
    string msg = "";

    if (@item.Type == "start")
    {
        status = "Started";
        msg = "Please Vote Here";
    }
    else if (@item.Type == "ended")
    {
        status = "Ended";
        msg = "You can watch the results";
    }

    <script type="text/javascript">
            Lobibox.notify('success', {
                position: 'bottom right',
                title: '@item.Name'+' is just ' + '@status',
                size: 'mini',
                msg: '@msg'
            });
    </script>
}

OnlineElection/Views/Shared/_PollNotificationsList.cshtml
@model IEnumerable<OnlineElection.Domain.ViewModels.NotificationsViewModel>

@{
    if (Model != null)
    {
        foreach (var item in Model)
        {
            string status = "";
            string msg = "";

            if (@item.type == "start" || @item.type == "Start")
            {
                string timelong = "";
                TimeSpan time = DateTime.Now - DateTime.Parse(@item.date);
                double val = time.TotalMinutes;

                if (val < 50)
                {
                    timelong = Math.Round(val).ToString() + " minutes ago";
                }
                else if (time.TotalHours < 24)
                {
                    timelong = Math.Round(time.TotalHours).ToString() + " hours ago";
                }
                else if (time.TotalDays < 30)
                {
                    timelong = Math.Round(time.TotalDays).ToString() + " days ago";
                }
                else
                {
                    timelong = Math.Round(time.TotalDays/30).ToString() + " months ago";
                }

                status = "Started " + timelong;
                msg = "Please Vote Here";
            }
            else if (@item.type == "ended")
            {
                string timelong = "";
                TimeSpan time = DateTime.Now - DateTime.Parse(@item.date);
                double val = time.TotalMinutes;
                if (val < 50)
                {
                    timelong = Math.Round(val).ToString() + " minutes ago";
                }
                else if (time.TotalHours < 24)
                {
                    timelong = Math.Round(time.TotalHours).ToString() + " hours ago";
                }
                else if (time.TotalDays < 30)
                {
                    timelong = Math.Round(time.TotalDays).ToString() + " days ago";
                }
                else
                {
                    timelong = Math.Round(time.TotalDays / 30).ToString() + " months ago";
                }


                status = "Ended " + timelong;
                msg = "Just Go and See the Results in few minutes";
            }


            <div style="float:left;border-style:groove;width:100%" class="row">
                <p style="float:left">
                    @item.Name Poll is @status
                    <br />
                    @msg
                </p>
            </div>

        }

    }
    else
    {
        <div style = "float:left;border-style:groove;width:100%" class="row">
            <p style = "float:left" >
                No notifications
            </p>
        </div>
    }
    }